### ISSUE TITLE
Upgrading from TotalRisk-1.2.61 to TotalRisk-1.2.96

### ISSUE THREAD

**Issue by drdalan** [ToWelie89/TotalRisk#1] opened 2019-07-09 22:52 UTC
Hello,

I've been running your risk game for a few months now, downloaded the new version 1.2.96, I am unable to get npm start to work on the local server. Here is the output from my server.

[Console output.txt](https://github.com/ToWelie89/TotalRisk/files/3375025/Console.output.txt)

My server Ubuntu 18.10
npm version 5.8.0

I'm a network engineer, and use your risk game to test network flaws and monitor server traffic. Also it's nice to play a quick 15 minute game while waiting for something to install or load.

Thank you, Dalan.

**Comment by ToWelie89** [comment] 2019-07-09 22:54
Hello!

Cool, I didn't know anyone actually played my Risk game 😄 I know what the issue is. I will push a fix to it tomorrow. Please tell me if you find more issues 🙂

/Martin Sonesson

________________________________
Från: Dr Dalan <notifications@github.com>
Skickat: den 9 juli 2019 22:52
Till: ToWelie89/TotalRisk
Kopia: Subscribed
Ämne: [ToWelie89/TotalRisk] Upgrading from TotalRisk-1.2.61 to TotalRisk-1.2.96 (#1)


Hello,

I've been running your risk game for a few months now, downloaded the new version 1.2.96, I am unable to get npm start to work on the local server. Here is the output from my server.

Console output.txt<https://github.com/ToWelie89/TotalRisk/files/3375025/Console.output.txt>

My server Ubuntu 18.10
npm version 5.8.0

I'm a network engineer, and use your risk game to test network flaws and monitor server traffic. Also it's nice to play a quick 15 minute game while waiting for something to install or load.

Thank you, Dalan.

**Comment by ToWelie89** [comment] 2019-07-09 23:57
> Hello,
> 
> I've been running your risk game for a few months now, downloaded the new version 1.2.96, I am unable to get npm start to work on the local server. Here is the output from my server.
> 
> [Console output.txt](https://github.com/ToWelie89/TotalRisk/files/3375025/Console.output.txt)
> 
> My server Ubuntu 18.10
> npm version 5.8.0
> 
> I'm a network engineer, and use your risk game to test network flaws and monitor server traffic. Also it's nice to play a quick 15 minute game while waiting for something to install or load.
> 
> Thank you, Dalan.

It is fixed now. Simply pull the latest changes and you should be able to run it.

I've made some changes since 1.2.61 though. Now  you need to run
```
npm start
```
in one terminal to start the web server. Then you can run the game in your browser (localhost:5000) or you can start another terminal and run
```
npm run electron:dev
```
(this may require you to have electron installed globally)

**Closed** 2019-07-09 23:58 UTC
